language: node_js
cache:
  - npm
node_js:
  - "node"
git:
  depth: 3
notifications:
  email:
    on_success: never
install:
  - npm install -g firebase-tools jshint
script: jshint public
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}
